version: 2

updates:
# keep up to date the github actions
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: monthly
    timezone: Europe/Rome
  groups:
    minor-actions-dependencies:
      update-types:
      - minor
      - patch
  commit-message:
    include: scope
    prefix: ci

# keep up to date the base docker image ignoring major versions
- package-ecosystem: docker
  directory: /
  schedule:
    interval: daily
    time: "07:00"
    timezone: Europe/Rome
  commit-message:
    include: scope
    prefix: build
  ignore:
  - dependency-name: '*'
    update-types:
    - version-update:semver-major

# enable npm dependencies security updates
- package-ecosystem: npm
  open-pull-requests-limit: 0
  rebase-stategy: auto
  directory: /
  schedule:
    interval: daily
    time: "07:00"
    timezone: Europe/Rome
  commit-message:
    include: scope
    prefix: feat

# keep up to date devcontainers
- package-ecosystem: devcontainers
  directory: /
  schedule:
    interval: monthly
    timezone: Europe/Rome
  commit-message:
    include: scope
    prefix: build
